version: '3.8'

services: 
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - node-network
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      
  node:
    build: 
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s ./.docker/entrypoint.sh
    container_name: node
    volumes: 
      - ./node:/usr/src/app
    networks: 
      - node-network
    tty: true
    expose: 
      - "3000"
    depends_on: 
      - db

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
      - node

networks: 
  node-network:
    driver: bridge     
